
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class SAGRADOGUI extends javax.swing.JFrame {

    /**
     * Creates new form SAGRADOGUI
     */
    public SAGRADOGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        fullname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bb = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        rb = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        wm = new javax.swing.JCheckBox();
        password = new javax.swing.JPasswordField();
        dc = new javax.swing.JCheckBox();
        confirmpassword = new javax.swing.JPasswordField();
        eat = new javax.swing.JCheckBox();
        sg = new javax.swing.JCheckBox();
        courseComboBox = new javax.swing.JComboBox<>();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("NETFLIX");

        email.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        fullname.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        fullname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Fullname");

        signup.setBackground(new java.awt.Color(204, 0, 0));
        signup.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        signup.setText("Sign Up");
        signup.setBorder(new javax.swing.border.MatteBorder(null));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Email address");

        bb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bb.setText("BASKETBALL");
        bb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        rb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rb.setText("READING BOOKS ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Confirm password");

        wm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        wm.setText("WATCHING MOVIE");

        dc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dc.setText("DANCING");

        eat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eat.setText("EATING");
        eat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eatActionPerformed(evt);
            }
        });

        sg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sg.setText("SINGING");

        courseComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE COURSE", "BSBA", "BSIT", "BSCRIM", "BSEDUC" }));
        courseComboBox.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });

        male.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        male.setText("MALE");
        male.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        female.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        female.setText("FEMALE");
        female.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(male)
                                .addGap(42, 42, 42)
                                .addComponent(female))
                            .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(password)
                                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bb)
                                    .addComponent(dc))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eat)
                                    .addComponent(rb)))
                            .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wm)
                            .addComponent(sg)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bb)
                        .addComponent(rb)
                        .addComponent(wm)
                        .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dc)
                    .addComponent(eat)
                    .addComponent(sg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female))
                .addGap(50, 50, 50)
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        String fn = fullname.getText();
        String eml = email.getText();
        String pass = password.getText();
        String pass2 = confirmpassword.getText();
    
    if (eml.isEmpty() || pass.isEmpty() || pass2.isEmpty() || fn.isEmpty()) {
        fullname.setBackground(Color.RED);
        email.setBackground(Color.RED);
        password.setBackground(Color.RED);
        confirmpassword.setBackground(Color.RED);
        System.out.println("Please fill in all fields.");
        return;
    }
    
    if (!isValidString(fn)) {
        fullname.setBackground(Color.RED);
        System.out.println("Enter valid fullname.");
        return;
        }

       if (!pass.equals(pass2)) {
        
        confirmpassword.setBackground(Color.RED); 
        System.out.println("Passwords do not match. Please try again.");
        return;
    }

    if (!isValidEmail(eml)) {
        email.setBackground(Color.RED);
        System.out.println("Invalid email format. Please enter a valid email.");
        return;
    }
    
        String course = (String) courseComboBox.getSelectedItem();
    if (course.equals("CHOOSE COURSE")) {
        System.out.println("Please select a course.");
        return;
    }
    
    String gender = "";
    if (male.isSelected()) {
        gender = "Male";
    } else if (female.isSelected()) {
        gender = "Female";
    } else {
        System.out.println("Please select a gender.");
        return;
    }

    String hobbies = "";
    if (rb.isSelected()) {
        hobbies += "Reading Book, ";
    }
    if (bb.isSelected()) {
        hobbies += "Basketball, ";
    }
    if (dc.isSelected()) {
        hobbies += "Dancing, ";
    }
    if (sg.isSelected()) {
        hobbies += "Swimming, ";
    }
    if (eat.isSelected()) {
        hobbies += "Eat, ";
    }
    if (sg.isSelected()) {
        hobbies += "Singing, ";
    }
    if (wm.isSelected()) {
        hobbies += "Watching Movies, ";
    }
    if (hobbies.isEmpty()) {
        System.out.println("Please select at least one hobby.");
        return;
    }

    String directoryPath = "C:\\Users\\USER\\Documents\\form";
    new java.io.File(directoryPath).mkdirs();

    String filePath = directoryPath + "\\" + eml + ".txt";
    
    if (new java.io.File(filePath).exists()) {
        email.setBackground(Color.RED);
        System.out.println("Email already exists, please use a new one.");
        return;
    }

    try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
        writer.write("Fullname: " + fn);
        writer.newLine();
        writer.write("Username: " + eml);
        writer.newLine();
        writer.write("Password: " + pass);
        writer.newLine();
        writer.write("Gender: " + gender);
        writer.newLine();
        writer.write("Hobbies: " + hobbies);
        writer.newLine();
        writer.write("Course: " + course);
        writer.newLine();
        System.out.println("Account created successfully!");

        email.setBackground(null);
        fullname.setBackground(null);
        password.setBackground(null);
        confirmpassword.setBackground(null);
        
        

    } catch (IOException e) {
        e.printStackTrace();
     }
        LOGIN login = new LOGIN();
        login.setVisible(true);
        login.show();
        this.hide();
    }//GEN-LAST:event_signupActionPerformed

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseComboBoxActionPerformed

    private void eatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eatActionPerformed

        private boolean isValidEmail(String email) {
    return email.matches("^[A-Za-z0-9._%+-]+@(gmail|yahoo)\\.com$");
}
        private boolean isValidString(String input) {
    return input.matches("^[a-zA-Z ]+$");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SAGRADOGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SAGRADOGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SAGRADOGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAGRADOGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SAGRADOGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bb;
    private javax.swing.JPasswordField confirmpassword;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JCheckBox dc;
    private javax.swing.JCheckBox eat;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton male;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox rb;
    private javax.swing.JCheckBox sg;
    private javax.swing.JButton signup;
    private javax.swing.JCheckBox wm;
    // End of variables declaration//GEN-END:variables
}
